apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ge-openshift-metering
  namespace: openshift-metering
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  channel: "4.5"
  name: metering-ocp
  source: redhat-operators
  sourceNamespace: openshift-marketplace
