apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.8.7

namespace: argocd

secretGenerator:
  - name: argocd-secret
    behavior: merge
    literals:
### create hash: htpasswd -bnBC 10 "" admin | tr -d ':\n'
      - admin.password=$2y$10$KCUOEvfMR6/zTjiB4yDI0eyU3Oyul9DeDkcpKZZhW3wEHKmw1SZwa
      - admin.passwordMtime=2000-01-01T00:00:00Z
      - server.secretkey=seeyiiceifeeViChiegh2sae5eigh8Aib0eel4ooc5Oazaeg7i
    type: Opaque

patchesStrategicMerge:
  - argocd-cm.yaml
  - deployment-argocd-server.yaml

resources:
  - route-argocd.yaml
  - namespace-argocd.yaml

generatorOptions:
  disableNameSuffixHash: true
